config/routes.rb
Hrt::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  match 'users/sign_out' => 'static_page#sign_out'
  resources :invitations, only: [:edit, :update]

  root to: 'static_page#index'
  resource :profile, only: [:disable_tips] do
    member do
      put :disable_tips
    end
  end
  match 'about' => 'static_page#about', as: :about_page
  resources :comments, :only => [:edit, :create, :update, :destroy]
  match 'dashboard' => 'dashboard#index', as: :dashboard
  namespace :admin do
    resources :requests
    resources :responses, only: [:index, :new, :create, :destroy] do
      collection do
        get :export
      end
    end
    resources :organizations do
      collection do
        get :duplicate
        put :remove_duplicate
        get :download_template
        post :create_from_file
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :locations
        get :district_workplan
        get :funders
        get :reporters
      end
    end
    namespace :reports do
      resources :detailed, only: [:index, :show] do
        collection do
          put :mark_double_counts
        end
        member do
          get :generate
        end
      end
    end
    resources :documents, path: 'files'
    resources :currencies, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :create_from_file
        get :download_template
      end
    end
    resources :locations, only: [:index, :edit, :update]
    resources :purposes, only: [:index, :edit, :update]
    resources :inputs, only: [:index, :edit, :update]
    resources :beneficiaries, only: [:index, :edit, :update]
  end

  resources :workplans  do
    collection do
      get :download
      get :generate
    end
  end

  resources :responses, :only => [] do
    member do
      get :review
      put :submit
      put :send_data_response
      get :reject
      get :accept
      get :generate_overview
      get :download_overview
    end
  end
  resources :projects, except: [:show] do
    collection do
      get :download_template
      get :export_workplan
      get :export
      post :import
    end
  end
  resources :activities, except: [:index, :show]
  resources :other_costs, except: [:index, :show] do
    collection do
      post :create_from_file
      get :download_template
    end
  end
  resources :organizations, only: [:index, :edit, :update] do
    collection do
      get :export
    end
  end
  resources :documents
  resources :reports, only: [:index] do
    collection do
      get :inputs
      get :locations
      get :projects
    end
  end

  namespace :reports do
    resources :activities, only: [:show] do
      member do
        get :implementers
        get :inputs
        get :locations
      end
    end
    resources :projects, only: [:show] do
      member do
        get :activities
        get :locations
        get :inputs
      end
    end
  end
end

app/models/beneficiary.rb
class Beneficiary < ActiveRecord::Base
  extend CodeVersion

  ### Attributes
  attr_accessible :name

  ### Validations
  validates :name, presence: true
  validates :version, presence: true

  ### Associations
  has_and_belongs_to_many :activities # organizations targeted by this activity / aided

end

app/controllers/admin/beneficiaries_controller.rb
class Admin::BeneficiariesController < Admin::BaseController

  ### Inherited Resources
  inherit_resources

  def index
    @beneficiaries = Beneficiary.with_last_version.order("id ASC")

    if params[:query].present?
      @beneficiaries = @beneficiaries.where(["UPPER(name) LIKE UPPER(:q)",
                              {q: "%#{params[:query]}%"}])
    end
  end

  def update
    update! do |success, failure|
      success.html do
        flash[:notice] = "Beneficiary was successfully updated"
        redirect_to edit_admin_beneficiary_url(resource)
      end
    end
  end

end

app/views/admin/beneficiaries/_form.html.haml
= f.inputs :class => 'inputs' do
  %li.last
    %ul.section_form.first
      = f.input :name, :required => false, :hint => "Name of the beneficiary"

  %li.last
    %ul.horizontal.section_form.last.connect
      = f.actions :class => 'buttons' do
        = f.action :submit, :label => (@beneficiary.new_record? ? "Create New Beneficiary" : "Update Beneficiary"), :button_html => {:class => 'next'}

app/views/admin/beneficiaries/_row.html.haml
%li
  %div.clearfix
    %span
    = link_to beneficiary.name, edit_admin_beneficiary_path(beneficiary), :class => "code-label"

app/views/admin/beneficiaries/edit.html.haml
- title("Edit Beneficiary")

%h1.main_heading Edit Beneficiary

= render 'shared/error_messages', :resource => @beneficiary

= semantic_form_for @beneficiary, :url => admin_beneficiary_path(@beneficiary), :html => {:method => :put, :class => "basic_form js_form"} do |f|
  = render 'form', :f => f

app/views/admin/beneficiaries/index.html.haml
= render :partial => 'admin/shared/codes_menu'

.section_form.single.connect.topless
  #search.push
    = form_tag admin_beneficiaries_path, method: :get do
      = render 'shared/search_form'

  %ul.activity_tree
    - @beneficiaries.each do |beneficiary|
      = render 'row', beneficiary: beneficiary