config/routes.rb
Hrt::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  match 'users/sign_out' => 'static_page#sign_out'
  resources :invitations, only: [:edit, :update]

  root to: 'static_page#index'
  resource :profile, only: [:disable_tips] do
    member do
      put :disable_tips
    end
  end
  match 'about' => 'static_page#about', as: :about_page
  resources :comments, :only => [:edit, :create, :update, :destroy]
  match 'dashboard' => 'dashboard#index', as: :dashboard
  namespace :admin do
    resources :requests
    resources :responses, only: [:index, :new, :create, :destroy] do
      collection do
        get :export
      end
    end
    resources :organizations do
      collection do
        get :duplicate
        put :remove_duplicate
        get :download_template
        post :create_from_file
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :locations
        get :district_workplan
        get :funders
        get :reporters
      end
    end
    namespace :reports do
      resources :detailed, only: [:index, :show] do
        collection do
          put :mark_double_counts
        end
        member do
          get :generate
        end
      end
    end
    resources :documents, path: 'files'
    resources :currencies, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :create_from_file
        get :download_template
      end
    end
    resources :locations, only: [:index, :edit, :update]
    resources :purposes, only: [:index, :edit, :update]
    resources :inputs, only: [:index, :edit, :update]
    resources :beneficiaries, only: [:index, :edit, :update]
  end

  resources :workplans  do
    collection do
      get :download
      get :generate
    end
  end

  resources :responses, :only => [] do
    member do
      get :review
      put :submit
      put :send_data_response
      get :reject
      get :accept
      get :generate_overview
      get :download_overview
    end
  end
  resources :projects, except: [:show] do
    collection do
      get :download_template
      get :export_workplan
      get :export
      post :import
    end
  end
  resources :activities, except: [:index, :show]
  resources :other_costs, except: [:index, :show] do
    collection do
      post :create_from_file
      get :download_template
    end
  end
  resources :organizations, only: [:index, :edit, :update] do
    collection do
      get :export
    end
  end
  resources :documents
  resources :reports, only: [:index] do
    collection do
      get :inputs
      get :locations
      get :projects
    end
  end

  namespace :reports do
    resources :activities, only: [:show] do
      member do
        get :implementers
        get :inputs
        get :locations
      end
    end
    resources :projects, only: [:show] do
      member do
        get :activities
        get :locations
        get :inputs
      end
    end
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  extend CodeVersion

  ### Attributes
  attr_accessible :name

  ### Validations
  validates :name, presence: true
  validates :version, presence: true

  # Associations
  has_many :code_splits, as: :code, dependent: :destroy
  # has_many :activities, :through => :code_splits

  ### Scopes
  scope :national_level, { conditions: "lower(locations.name) = 'national level'" }
  scope :without_national_level, { conditions: "lower(locations.name) != 'national level'" }
  scope :sorted, { order: "UPPER(locations.name)" }
  scope :roots
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < Admin::BaseController

  ### Inherited Resources
  inherit_resources

  def index
    @locations = Location.with_last_version.order("name ASC")

    if params[:query].present?
      @locations = @locations.where(["UPPER(name) LIKE UPPER(:q)",
                              {q: "%#{params[:query]}%"}])
    end
  end

  def update
    update! do |success, failure|
      success.html do
        flash[:notice] = "Location was successfully updated"
        redirect_to edit_admin_location_url(resource)
      end
    end
  end
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/_form.html.haml
= f.inputs :class => 'inputs' do
  %li.last
    %ul.section_form.first
      = f.input :name, :required => false, :hint => "Name of the location"

  %li.last
    %ul.horizontal.section_form.last.connect
      = f.actions :class => 'buttons' do
        = f.action :submit, :label => (@location.new_record? ? "Create New Location" : "Update Location"), :button_html => {:class => 'next'}

app/views/admin/locations/_row.html.haml
%li
  %div.clearfix
    %span
    = link_to location.name, edit_admin_location_path(location), :class => "code-label"

app/views/admin/locations/edit.html.haml
- title("Edit Location")

%h1.main_heading Edit Location

= render 'shared/error_messages', :resource => @location

= semantic_form_for @location, :url => admin_location_path(@location), :html => {:method => :put, :class => "basic_form js_form"} do |f|
  = render 'form', :f => f

app/views/admin/locations/index.html.haml
= render :partial => 'admin/shared/codes_menu'

.section_form.single.connect.topless
  #search.push
    = form_tag admin_locations_path, method: :get do
      = render 'shared/search_form'

  %ul.activity_tree
    - @locations.each do |location|
      = render 'row', location: location