config/routes.rb
Hrt::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  match 'users/sign_out' => 'static_page#sign_out'
  resources :invitations, only: [:edit, :update]

  root to: 'static_page#index'
  resource :profile, only: [:disable_tips] do
    member do
      put :disable_tips
    end
  end
  match 'about' => 'static_page#about', as: :about_page
  resources :comments, :only => [:edit, :create, :update, :destroy]
  match 'dashboard' => 'dashboard#index', as: :dashboard
  namespace :admin do
    resources :requests
    resources :responses, only: [:index, :new, :create, :destroy] do
      collection do
        get :export
      end
    end
    resources :organizations do
      collection do
        get :duplicate
        put :remove_duplicate
        get :download_template
        post :create_from_file
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :locations
        get :district_workplan
        get :funders
        get :reporters
      end
    end
    namespace :reports do
      resources :detailed, only: [:index, :show] do
        collection do
          put :mark_double_counts
        end
        member do
          get :generate
        end
      end
    end
    resources :documents, path: 'files'
    resources :currencies, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :create_from_file
        get :download_template
      end
    end
    resources :locations, only: [:index, :edit, :update]
    resources :purposes, only: [:index, :edit, :update]
    resources :inputs, only: [:index, :edit, :update]
    resources :beneficiaries, only: [:index, :edit, :update]
  end

  resources :workplans  do
    collection do
      get :download
      get :generate
    end
  end

  resources :responses, :only => [] do
    member do
      get :review
      put :submit
      put :send_data_response
      get :reject
      get :accept
      get :generate_overview
      get :download_overview
    end
  end
  resources :projects, except: [:show] do
    collection do
      get :download_template
      get :export_workplan
      get :export
      post :import
    end
  end
  resources :activities, except: [:index, :show]
  resources :other_costs, except: [:index, :show] do
    collection do
      post :create_from_file
      get :download_template
    end
  end
  resources :organizations, only: [:index, :edit, :update] do
    collection do
      get :export
    end
  end
  resources :documents
  resources :reports, only: [:index] do
    collection do
      get :inputs
      get :locations
      get :projects
    end
  end

  namespace :reports do
    resources :activities, only: [:show] do
      member do
        get :implementers
        get :inputs
        get :locations
      end
    end
    resources :projects, only: [:show] do
      member do
        get :activities
        get :locations
        get :inputs
      end
    end
  end
end

app/controllers/outlays_controller.rb
class OutlaysController < BaseController
  helper_method :sort_column, :sort_direction

  before_filter :confirm_activity_type, only: [:edit]
  before_filter :prevent_activity_manager, only: [:create, :update, :destroy]

  protected

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  # TODO: refactor
  def prepare_classifications(outlay)
    # if we're viewing classification 'tabs'
    if ['locations', 'purposes', 'inputs'].include? params[:mode]
      mode = params[:mode].singularize.to_sym # :purpose, :input, :location
      code_type = mode.to_s.capitalize # Purpose, Input, Location

      @budget_coding_tree = CodingTree.new(outlay, mode, :budget)
      @spend_coding_tree  = CodingTree.new(outlay, mode, :spend)
      @budget_assignments = outlay.code_splits.with_code_type(code_type).budget.
                              map_to_hash { |b| { b.code_id => b } }
      @spend_assignments  = outlay.code_splits.with_code_type(code_type).spend.
                              map_to_hash { |b| { b.code_id => b } }

      # set default to 'all'
      params[:view] = 'all' if params[:view].blank?
    end
  end

  # run validations on the models independently of any save action
  # useful if you want to show (existing) errors without having to save the form first.
  def load_validation_errors(resource)
    resource.implementer_splits.find(:all, include: :organization).each {|is| is.valid?}
    resource.valid?
  end

  def on_implementers_page?
    params[:mode].blank? || params[:mode] == 'implementers'
  end

  def prepare_edit(outlay)
    warn_if_not_classified(outlay)
    prepare_classifications(outlay)
    load_comment_resources(outlay)
    load_validation_errors(outlay) if on_implementers_page?
    paginate_splits(outlay) if on_implementers_page?
  end

  def save_outlay(outlay)
    if outlay.save
      success_flash("created")
      html_redirect(outlay)
    else
      paginate_splits(outlay)
      render action: 'new'
    end
  end

  def update_outlay(outlay)
    attr = outlay.class.eql?(Activity) ? params[:activity] : params[:other_cost]

    classifications = attr[:classifications]
    attr.delete :classifications

    if outlay.update_attributes(attr) &&
      update_classifications(outlay, classifications)
        success_flash("updated")
        html_redirect(outlay)
    else
      prepare_edit(outlay)
      render action: 'edit'
    end
  end

  def html_redirect(outlay)
    mode = params[:mode]
    if params[:commit]
      ['locations', 'purposes', 'inputs', 'outputs'].each do |tab|
        if params[:commit].match /#{tab}/i
          mode = tab
        end
      end

      return redirect_to projects_path if params[:commit].match /Overview/
    end

    return redirect_to edit_activity_or_ocost_path(outlay, mode: mode)
  end

  private
  def update_classifications(outlay, classifications_params)
    return true if classifications_params.blank?

    code_type_key = classifications_params.keys.first.to_sym

    unless allowed_code_type_keys(outlay).include?(code_type_key)
      raise "Invalid code type key"
    end

    classifications = classifications_params[code_type_key]
    [:budget, :spend].each do |amount_type|
      classifier = Classifier.new(outlay, code_type_key, amount_type)
      classifier.update_classifications(classifications[amount_type])
    end
  end

  def allowed_code_type_keys(outlay)
    if outlay.is_a? Activity
      [:purpose, :input, :location]
    else
      [:input, :locations]
    end
  end

end

app/helpers/shared/outlays_helper.rb
module Shared::OutlaysHelper
  ACTIVITY_TABS = {
    implementers: 'Implementers',
    locations: 'Locations',
    purposes: 'Purposes',
    inputs: 'Inputs',
    outputs: 'Outputs, Targets & Beneficiaries'
  }

  INDIRECT_COST_TABS = {
    implementers: 'Implementers',
    locations: 'Locations',
    inputs: 'Inputs'
  }

  def sorted_project_select(response, klass, length = 60)
    list = response.projects.sort_by{ |p| p.name }.collect do |u|
      [ truncate(u.name, length: length), u.id ]
    end
    blank_name = klass == "OtherCost" ? "Not project-specific" :  ""
    list.insert(0,[blank_name, nil])
  end

  def selected_project(project)
    if params[:project_id].present?
      params[:project_id]
    else
      project ? project.id : nil
    end
  end

  def tab_class(tab)
    if params[:mode]
      params[:mode] == (tab.to_s) ? 'selected' : nil
    else
      'selected' if tab == :implementers
    end
  end

  # other costs do not show Purposes/Inputs/Outputs tabs
  def save_and_add_button_text(current_step, outlay)
    current_step ||= 'implementers'
    current_index = tabs(outlay).keys.index(current_step.to_sym)
    if current_index == tabs(outlay).size - 1
      "Save & Go to Overview >"
    else
      "Save & Add #{tabs(outlay).values[current_index + 1]} >"
    end
  end

  def tabs(outlay)
    if outlay.class == Activity
      Shared::OutlaysHelper::ACTIVITY_TABS
    else
      Shared::OutlaysHelper::INDIRECT_COST_TABS
    end
  end
end

app/views/shared/outlays/_activity_basic_fields.html.haml
- klass = outlay.type

%ul.section_form.first.condensed_fields
  = f.hidden_field :data_response_id, :value => current_response.id
  %li#activity_name_input.string.required
    .name
      = f.label :name, "Name"
      %span.required *
      = link_to "#", :title => "A short name for this #{klass}", :class => 'tooltip remaining_characters' do
        =image_tag"tooltip.png"
    = f.text_field :name, :size => "80", "data-maxlength" => "#{Activity::MAX_NAME_LENGTH}"

  %li#activity_project_id_input.select.required
    .name
      = f.label :project_id, "Project"
      %span.required *
      = link_to "#", :title => "The Project which this #{klass} belongs to", :class => 'tooltip' do
        =image_tag"tooltip.png"
    = f.select :project_id, options_for_select(sorted_project_select(@response, klass), selected_project(f.object.project)), {}, :class => f.object.errors[:project_id].present? ? "error" : ""
  %li.select.required
    .name
      = f.label :currency, "Currency"
      = link_to "#", :title => "The default (Organization) currency or the Project currency, if selected", :class => 'tooltip' do
        = image_tag "tooltip.png"
    %span.noedit= f.object.currency.nil? ? @response.currency : f.object.currency

  //hack
  %br
  %li#activity_description_input.text
    .name
      = f.label :description, "Description"
      %span.required *
      = link_to "#", :title => "A general 1-2 sentence description of the purpose of the #{klass}.", :class => 'tooltip' do
        =image_tag"tooltip.png"
    = f.text_area :description, :rows => 1, :class => f.object.errors[:description].present? ? "error" : ""

app/views/shared/outlays/_classification.html.haml
- @outlay_klass = outlay.class.to_s.underscore

%ul.horizontal.button-bar
  %li= link_to 'Show mine', edit_activity_or_ocost_path(outlay, mode: params[:mode], view: 'my'), class: (params[:view] == 'my' ? 'active create_alt' : 'create_alt')

  %li= link_to 'Show all', edit_activity_or_ocost_path(outlay, mode: params[:mode], view: 'all'), class: (params[:view] == 'all' ? 'active create_alt' : 'create_alt')
  - if params["mode"] != "inputs" && params["mode"] != "purposes"
    %li
      = link_to "#", class: "create_alt js_upload_btn" do
        = image_tag "new.png"
        Upload

- heading_hint = "The percentage of the total activity amount."
- unless params[:mode] == 'locations'
  - heading_hint += " Enter the most detailed level first, and we'll roll it up for you automatically."
- if @budget_coding_tree.root_codes.present?
  .copy_budget
    - alt_txt = "Copy across Budget classifications to Expenditure classifications"
    = link_to '#', id: 'js_budget_to_spend', alt: alt_txt, title: alt_txt do
      &nbsp; <!-- fix for poltergeist javascript driver -->
      = image_tag("icon_b2s.png", class: "click")
    %span Current Budget %
    = link_to image_tag("tooltip.png"), "#", title: heading_hint, class: 'tooltip right'
  .copy_spend
    %span Past Expenditure %
    = link_to image_tag("tooltip.png"), "#", title: heading_hint, class: 'tooltip'
    - alt_txt = "Copy across Expenditure classifications to Budget classifications"
    = link_to '#', id: 'js_spend_to_budget', alt: alt_txt, title: alt_txt do
      &nbsp; <!-- fix for poltergeist javascript driver -->
      = image_tag("icon_s2b.png", class: "click")

  %ul.activity_tree{activity_budget: outlay.total_budget, activity_spend: outlay.total_spend, activity_currency: outlay.currency}
    - @budget_coding_tree.root_codes.each do |code|
      = render 'shared/outlays/code_row', code: code, margin: 0, outlay: outlay

  .coding_total.right
    %p.value.left.js_total_spend
      %span.label.left Total
      %span.percentage.right= '%'
      %span.amount.right= codings_total(outlay, @spend_coding_tree.code_type_key, @spend_coding_tree.amount_type)

    %p.value.right.js_total_budget
      %span.label.left Total
      %span.percentage.right= '%'
      %span.amount.right= codings_total(outlay, @budget_coding_tree.code_type_key, @budget_coding_tree.amount_type)

app/views/shared/outlays/_code_row.html.haml
- classified = code_classified?(@budget_assignments, @spend_assignments, code)
- margin_max = 150
- margin_delta = 11

- if all_view? || classified
  %li
    %div.clearfix
      .code_label
        - id = "row[#{code.id}]"
        = check_box_tag id, code.id, classified, { tabindex: -1 }
        = image_tag "tooltip.png", title: code.description, class: "tooltip info" if code.respond_to?(:description) && code.description
        = label_tag id, code.name

      .values.js_values.right
        .classification_input_left
          .spend.js_spend{style: "width: #{margin_max-margin}px;"}
            - assignment = @spend_assignments[code.id]
            - cached_amount = assignment.nil? ? '' : assignment.cached_amount
            - cached_label = cached_amount.blank? ? "" : "#{n2c(cached_amount)}"
            - percentage = derive_percentage_from_amount(outlay, :total_spend, assignment)

            = text_field_tag "#{@outlay_klass}[classifications][#{@spend_coding_tree.code_type_key}][spend][#{code.id}]", h(percentage), {size: 5, class: "percentage_box js_spend"}
            .inline_ratio %
            %span{title: "#{n2cs(cached_amount, outlay.currency) if assignment}", class: "tooltip subtotal_icon hidden"} ¤

        .classification_input_right
          .budget.js_budget{style: "width: #{150-margin}px;"}
            - assignment = @budget_assignments[code.id]
            - cached_amount = assignment.nil? ? '' : assignment.cached_amount
            - cached_label = cached_amount.blank? ? "" : "#{n2c(cached_amount)}"
            - percentage = derive_percentage_from_amount(outlay, :total_budget, assignment)

            = text_field_tag "#{@outlay_klass}[classifications][#{@budget_coding_tree.code_type_key}][budget][#{code.id}]", h(percentage), {size: 5, class: "percentage_box js_budget"}
            .inline_ratio %
            %span{title: "#{n2cs(cached_amount, outlay.currency) if assignment}", class: "tooltip subtotal_icon hidden"} ¤

    - unless code.is_a?(Location)
      - unless code.leaf?
        %ul
          - @budget_coding_tree.cached_children(code).each do |child|
            = render 'shared/outlays/code_row', code: child, margin: margin + margin_delta, outlay: outlay

app/views/shared/outlays/_edit.html.haml
- klass = outlay.class
- form_path = klass == Activity ? activity_path(outlay, mode: params[:mode]) : other_cost_path(outlay, mode: params[:mode])

- content_for :sub_nav do
  = render partial: 'shared/sub_nav_projects'

- if !current_user.sysadmin? && !outlay.classified?
  = render '/shared/outlays/uncoded_overlay', outlay: outlay

%h1.main_heading
  = klass == Activity ? "Edit Activity" : "Edit Indirect Cost"
  %span= klass == Activity ? render('activities/help') : render('other_costs/help')

= render 'shared/error_messages', resource: outlay

= semantic_form_for outlay, url: form_path, html: {class: "basic_form js_form"} do |f|
  = render '/shared/outlays/form', f: f, outlay: outlay

- unless outlay.new_record?
  .delete_section
    = link_to "Delete this #{outlay.human_name}", form_path, data: { confirm: "Are you sure you want to delete this #{outlay.human_name}?" }, method: :delete, class: 'delete_action'
    %p
      %strong Warning:
      ="Once you delete an #{outlay.human_name}, you will lose all data associated with it. There is no undo."

= render 'shared/comments', comments: @comments

app/views/shared/outlays/_form.html.haml
:javascript
  var _response_id = "#{@response.id}";
  var _activity_id = "#{outlay.id}";

= f.inputs class: 'inputs' do
  %li.last
    = render 'shared/outlays/activity_basic_fields', f: f, outlay: outlay

  %li.last= render 'shared/outlays/tab_nav', outlay: outlay

  - if ['locations', 'purposes', 'inputs'].include? params[:mode]
    #classification.section_form.topless.wrapped.last
      #activity_classification
        %div.tab1{style: 'display: block'}
          = render 'shared/outlays/classification', outlay: outlay

  - elsif params[:mode].nil? || params[:mode] == 'implementers'
    %li.implementer_splits.last
      %ul.section_form.topless.wrapped.last
        = render 'shared/outlays/implementers', f: f, outlay: outlay, blank_rows: 3, bulk_review: false

  - elsif params[:mode] == 'outputs'
    %li.implementer_splits.last
      %ul.section_form.topless.wrapped.last
        = render 'shared/outlays/outputs_targets_benefs', f: f, outlay: outlay

  %li.last
    %ul.horizontal.section_form.last.connect
      = f.actions class: 'buttons1' do
        = f.action :submit, label: "Save", button_html: {class: "last next js_submit_btn"}
        = f.action :submit, label: save_and_add_button_text(params[:mode], outlay), button_html: {class: "next js_submit_btn"}
        %li
          = link_to "Cancel", projects_path, class: "js_toggle_projects_listing cancel"
        %li
          = image_tag "ajax-loader.gif", class: "ajax-loader", style: 'display: none;'

app/views/shared/outlays/_implementer_split_fields.html.haml
-# auto included by link_to_add_fields()

- error_class = ""
- error_class = "error" unless f.object.errors.empty?

%tr.fields{:class => error_class, :style => f.object.marked_for_destruction? ? "display: none;" : nil}
  %td.title
    = f.text_field :organization_mask, :value => f.object.organization.try(:name).presence || f.object.organization_temp_name.presence || f.object.organization_mask, :class => 'js_autocomplete bulk_organization_mask'
    - if f.object.errors[:organization_temp_name].present?
      = image_tag "tooltip.png", :title => "Cannot find organization '#{f.object.organization_temp_name}'", :class => 'tooltip-S input_error'
  %td= f.text_field :spend, :class => 'js_spend no_style'
  %td= f.text_field :budget, :class => 'js_budget no_style'
  %td.delete= link_to_remove_fields "x", f, {:class => 'delete_row totals_callback', :callback => 'updateTotalsValuesCallback'}

app/views/shared/outlays/_implementers.html.haml
- klass = outlay.class.to_s
- @splits ||= sort_splits(outlay.implementer_splits)
- # Can't paginate form if there are errors therefore only
- # show splits with errors if there are more than 50 errors

.wrapped.last
  - unless bulk_review || outlay.new_record? || @split_errors
    = will_paginate @splits

  - if @split_errors && @splits.size > 50
    #filter_help
      %p
        = "Showing #{pluralize(@split_errors.count, 'Implementer')} with errors"

  %table.input_table
    %thead
      %tr
        %th.title
          Implementer
          %span
            = link_to "#", :title => "Direct implementer ('service provider') for this #{klass}. i.e. your own organization or another organization that carried out this work e.g. a NGO, a Health Facility Institution, Government office, or a District.", :class => 'tooltip' do
              = image_tag "tooltip.png"
        %th
          .right_justified Past Expenditure
        %th
          .right_justified Current Budget
        %th.delete
    %tbody
      = f.semantic_fields_for :implementer_splits do |ff|
        - show_only_errors = @split_errors && ( @splits.size <= 50 || !ff.object.errors.empty?)
        = render 'shared/outlays/implementer_split_fields', :f => ff if (bulk_review || show_only_errors) || outlay.errors.empty?

      - if @splits.size < 50 || @split_errors
        - blank_rows.times do
          - f.object.implementer_splits.build unless f.object.implementer_splits.length > 0
          - new_object = f.object.class.reflect_on_association(:implementer_splits).klass.new
          = f.fields_for(:implementer_splits, new_object) do |builder|
            = render "shared/outlays/implementer_split_fields", :f => builder

      %tr.total
        %td
          - unless bulk_review
            %span= link_to_add_fields "Add Implementer", f, :implementer_splits, "shared/outlays/", :class => "create_alt marginless"

        %td
          %p.total.js_total_spend
            %span.label.left Total
            %span.amount.right= number_with_precision(outlay.implementer_splits_total(:spend), :precision => 2)
            %span.currency.right= outlay.currency
        %td
          %p.total.js_total_budget
            %span.label.left Total
            %span.amount.right= number_with_precision(outlay.implementer_splits_total(:budget), :precision => 2)
            %span.currency.right= outlay.currency
  - unless bulk_review || outlay.new_record? || @split_errors
    = will_paginate @splits

app/views/shared/outlays/_output_fields.html.haml
.fields.clearfix
  %ul.edit_block.clearfix
    %li
      = f.text_field :description, :class => 'js_target_field', :id => 'output_field'
      %span= link_to_remove_fields "x", f, :class => 'delete_inline'

app/views/shared/outlays/_outputs_targets_benefs.html.haml
%li
  .column2.borderless.targets.js_targets
    %h3= "Outputs (#{current_fy(@response)})"
    .section_form.last
      = f.semantic_fields_for :outputs do |ca|
        = render "shared/outlays/output_fields", :f => ca
      .add.push-12
        = link_to_add_fields "Add Output", f, :outputs, "shared/outlays/", :class => "create_alt marginless js_add_nested"

  .column2.last.borderless.targets.js_targets
    %h3= "Targets (#{next_fy(@response)})"
    .section_form.last
      = f.semantic_fields_for :targets do |ca|
        = render "shared/outlays/target_fields", :f => ca
      .add.push-12
        = link_to_add_fields "Add Target", f, :targets, "shared/outlays/", :class => "create_alt marginless js_add_nested"

%li
  .column2.borderless
    %h3 Beneficiaries
    %ul.section_form.last
      = f.input :beneficiaries, collection: Beneficiary.with_last_version, label: false, as: :check_boxes, wrapper_html: { :class => 'borderless beneficiaries_boxes' }
      = f.input :other_beneficiaries, :label => 'Other Beneficiaries' , :input_html => { :rows => 2 }, :as => :text, :required => false, :wrapper_html => { :class => 'other_beneficiaries' }

  .column2.last.borderless
    - hint = 'Indicate whether the activity is planned to be implemented in any of these Government Of Rwanda Fiscal Quarters'
    %h3
      Planned Dates
      = link_to image_tag("tooltip.png"), "#", :title => hint, :class => 'tooltip'
    %fieldset.section_form.last
      %ol.planned_dates_boxes
        %label
          %strong Current Year:
        %li
          = f.check_box :planned_for_gor_q1, :class => 'left'
          = f.label :planned_for_gor_q1, "July - September"
        %li
          = f.check_box :planned_for_gor_q2, :class => 'left'
          = f.label :planned_for_gor_q2, "October - December"
        %label
          %strong Following Year:
        %li
          = f.check_box :planned_for_gor_q3, :class => 'left'
          = f.label :planned_for_gor_q3, "January - March"
        %li
          = f.check_box :planned_for_gor_q4, :class => 'left'
          = f.label :planned_for_gor_q4, "April - June"

app/views/shared/outlays/_tab_nav.html.haml
- is_activity = outlay.class == Activity ? true : false

.section_overlap
  %ul.section_nav
    - if outlay.new_record?
      - tabs(outlay).values.each_with_index do |tab, index|
        %li{:class => index == 0 ? 'selected' : ''}
          .dummy
            %span= index + 1
            = tab
    - else
      - tabs(outlay).each_with_index do |tab, index|
        %li{:class => tab_class(tab[0])}
          = link_to edit_activity_or_ocost_path(outlay, :mode => tab[0]) do
            %span= index + 1
            = tab[1]

app/views/shared/outlays/_target_fields.html.haml
.fields.clearfix

  %ul.edit_block.clearfix
    %li
      = f.text_field :description, :class => 'js_target_field', :id => 'target_field'
      %span= link_to_remove_fields "x", f, :class => 'delete_inline'

app/views/shared/outlays/_uncoded_overlay.haml
- colspan = 0
- is_other_cost = outlay.class == OtherCost ? true : false
- ["purposes", "locations", "inputs"].each do |request|
  - colspan += 1
  - colspan -= 1 if request == "locations" && is_other_cost

#uncoded_overlay.simple_overlay
  %ul.review
    %li
      %h3{:class => ready(false)}
        - if outlay.class == OtherCost
          Indirect Cost Classification
        - else
          Activity Classification
        %span.info
          Unchecked boxes mean that classification has not been started, or does not add up to 100%.

  %table.standard.push
    %thead
      %tr
        %th
        %th Locations
        - unless is_other_cost
          %th Purposes
          %th Inputs
    %tbody
      %tr
        %td Past Expenditure
        %td
          = check_box_tag "spend_locations", "", outlay.location_spend_splits_valid?, disabled: true
        - unless is_other_cost
          %td=check_box_tag "spend_purposes", "", outlay.purpose_spend_splits_valid?, disabled: true
        %td= check_box_tag "spend_inputs", "", outlay.input_spend_splits_valid?, disabled: true

      %tr
        %td Current Budget
        %td
          = check_box_tag "budget_locations", "", outlay.location_budget_splits_valid?, disabled: true
        - unless is_other_cost
          %td= check_box_tag "budget_purposes", "", outlay.purpose_budget_splits_valid?, disabled: true
        %td= check_box_tag "budget_inputs", "", outlay.input_budget_splits_valid?, disabled: true