config/routes.rb
Hrt::Application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  match 'users/sign_out' => 'static_page#sign_out'
  resources :invitations, only: [:edit, :update]

  root to: 'static_page#index'
  resource :profile, only: [:disable_tips] do
    member do
      put :disable_tips
    end
  end
  match 'about' => 'static_page#about', as: :about_page
  resources :comments, :only => [:edit, :create, :update, :destroy]
  match 'dashboard' => 'dashboard#index', as: :dashboard
  namespace :admin do
    resources :requests
    resources :responses, only: [:index, :new, :create, :destroy] do
      collection do
        get :export
      end
    end
    resources :organizations do
      collection do
        get :duplicate
        put :remove_duplicate
        get :download_template
        post :create_from_file
      end
    end
    resources :reports, only: [:index] do
      collection do
        get :locations
        get :district_workplan
        get :funders
        get :reporters
      end
    end
    namespace :reports do
      resources :detailed, only: [:index, :show] do
        collection do
          put :mark_double_counts
        end
        member do
          get :generate
        end
      end
    end
    resources :documents, path: 'files'
    resources :currencies, except: [:show]
    resources :users, except: [:show] do
      collection do
        post :create_from_file
        get :download_template
      end
    end
    resources :locations, only: [:index, :edit, :update]
    resources :purposes, only: [:index, :edit, :update]
    resources :inputs, only: [:index, :edit, :update]
    resources :beneficiaries, only: [:index, :edit, :update]
  end

  resources :workplans  do
    collection do
      get :download
      get :generate
    end
  end

  resources :responses, :only => [] do
    member do
      get :review
      put :submit
      put :send_data_response
      get :reject
      get :accept
      get :generate_overview
      get :download_overview
    end
  end
  resources :projects, except: [:show] do
    collection do
      get :download_template
      get :export_workplan
      get :export
      post :import
    end
  end
  resources :activities, except: [:index, :show]
  resources :other_costs, except: [:index, :show] do
    collection do
      post :create_from_file
      get :download_template
    end
  end
  resources :organizations, only: [:index, :edit, :update] do
    collection do
      get :export
    end
  end
  resources :documents
  resources :reports, only: [:index] do
    collection do
      get :inputs
      get :locations
      get :projects
    end
  end

  namespace :reports do
    resources :activities, only: [:show] do
      member do
        get :implementers
        get :inputs
        get :locations
      end
    end
    resources :projects, only: [:show] do
      member do
        get :activities
        get :locations
        get :inputs
      end
    end
  end
end

app/controllers/admin/organizations_controller.rb
require 'set'

class Admin::OrganizationsController < Admin::BaseController
  SORTABLE_COLUMNS  = ['name', 'raw_type', 'fosaid', 'created_at']

  ### Inherited Resources
  inherit_resources

  helper_method :sort_column, :sort_direction
  before_filter :load_organization, :only => [:edit, :update]
  before_filter :load_users, :only => [:edit, :update]

  def index
    scope = scope_organizations(params[:filter])
    if params[:query]
      scope = scope.where(["UPPER(organizations.name) LIKE UPPER(:q) OR
                            UPPER(organizations.raw_type) LIKE UPPER(:q) OR
                            UPPER(organizations.fosaid) LIKE UPPER(:q)",
                            {:q => "%#{params[:query]}%"}])
    end
    @organizations = scope.paginate(:page => params[:page], :per_page => 100,
                    :include => :users,
                    :order => "#{sort_column_query} #{sort_direction}, id ASC")
  end

  def show
    @target = Organization.find(params[:id], :include => [:projects,
      :activities, :users])
    @duplicate = Organization.find(params[:duplicate_id], :include => [:projects,
      :activities, :users])
    render :partial => 'organization_info'
  end

  def create
    create! do |success, failure|
      success.html do
        flash[:notice] = "Organization was successfully created"
        redirect_to edit_admin_organization_url(resource)
      end
    end
  end

  def update
    @organization.attributes = params[:organization]
    if @organization.save
      flash[:notice] = 'Organization was successfully updated'
      redirect_to edit_admin_organization_url(resource)
    else
      render :edit
    end
  end

  def destroy
    @organization = Organization.find(params[:id])

    if @organization.destroy
      flash[:notice] = "Organization was successfully destroyed."
      redirect_to admin_organizations_url
    else
      flash[:error] = "You cannot delete an organization with users or external reference data (i.e. funders/implementers)."
      redirect_to edit_admin_organization_url(@organization)
    end
  end

  def duplicate
    @all_organizations = Organization.ordered
  end

  def remove_duplicate
    merger = OrganizationMerger.new(
      params[:target_organization_id], params[:duplicate_organization_id])
    if merger.merge
        render_notice("Organizations successfully merged.",
                        duplicate_admin_organizations_path)
    else
      render_error(merger.error, duplicate_admin_organizations_path)
    end
  end

  def download_template
    report = Reports::Templates::Organizations.new([], 'csv')
    send_report_file(report, 'organization_template.csv')
  end

  def create_from_file
    begin
      if params[:file].present?
        doc = FileParser.parse(params[:file].open.read, 'csv', {:headers => true})
        if doc.headers.to_set == Organization::FILE_UPLOAD_COLUMNS.to_set
          saved, errors = Organization.create_from_file(doc)
          flash[:notice] = "Created #{saved} of #{saved + errors} organizations successfully"
        else
          flash[:error] = 'Wrong fields mapping. Please download the CSV template'
        end
      else
        flash[:error] = 'Please select a file to upload'
      end

      redirect_to admin_organizations_url
    rescue
      flash[:error] = "There was a problem with your file. Did you use the template and save it after making changes as a CSV file instead of an Excel file? Please post a problem at <a href='https://hrtapp.tenderapp.com/kb'>TenderApp</a> if you can't figure out what's wrong."
      redirect_to admin_organizations_url
    end
  end

  private

    def load_organization
      @organization = Organization.find(params[:id])
    end

    def load_users
      @users = @organization.users
    end

    def render_error(message, path)
      respond_to do |format|
        format.html do
          flash[:error] = message
          redirect_to path
        end
        format.js do
          render :remove_duplicate_error, :locals => { message: message }
        end
      end
    end

    def render_notice(message, path)
      respond_to do |format|
        format.html do
          flash[:notice] = message
          redirect_to path
        end
        format.js do
          render :remove_duplicate_notice, :locals => { message: message }
        end
      end
    end

    def sort_column
      SORTABLE_COLUMNS.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_column_query
      col = "organizations.#{sort_column}"
      col = "UPPER(#{col})" unless col == "organizations.created_at"
      col
    end

    def sort_direction
      direction = sort_column == "created_at" ? "desc" : "asc"
      %w[asc desc].include?(params[:direction]) ? params[:direction] : direction
    end

    # show reporting orgs by default.
    def scope_organizations(filter)
      case filter
      when 'Non-Reporting'
        Organization.nonreporting
      when 'Reporting'
        Organization.reporting
      when 'All'
        Organization.sorted
      else
        Organization.reporting
      end
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < BaseController

  before_filter :load_organization_details, only: [:edit, :update]

  def index
    organizations = Organization.active.find(:all,
      order: 'UPPER(name)', limit: 100,
      conditions: ["UPPER(organizations.name) LIKE UPPER(?)",
                      "%#{params[:term]}%"])

    respond_to do |format|
      format.json { render json: organizations.map(&:name) }
    end
  end

  def edit
    @organization.valid? # trigger validation errors
  end

  def update
    if @organization.update_attributes(params[:organization])
      flash[:notice] = "Settings were successfully updated."
      redirect_to edit_organization_path(:current)
    else
      flash.now[:error] = "Oops, we couldn't save your changes."
      render action: :edit
    end
  end

  def export
    if params[:type] == 'NGO'
      organizations = Organization.reporting.with_type("Donors").ordered + Organization.with_type("NGO").ordered
    elsif params[:type] == 'centers'
      organizations = Organization.reporting.with_type("District Hospital").ordered + Organization.with_type("Health Center").ordered
    else
      organizations = Organization.reporting.ordered
    end
    template = Organization.reporting.download_template(organizations)
    send_csv(template, 'organizations.csv')
  end

  private
    def load_organization_details
      @organization = @response.organization
      @activity_managers = @organization.managers.includes(:organization)
      @users = @organization.users.includes(:organization).order("full_name ASC")
    end
end

app/controllers/reports/organizations_controller.rb
class Reports::OrganizationsController < BaseController
  before_filter :load_response

  def overview
    @report = Reports::Organization.new(@response)
    render 'report'
  end
end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper

  def organization_name_w_num_users(organization)
    "#{friendly_name(organization, 255)} - #{pluralize(organization.users_count, 'user')}"
  end

  def search_and_filter_message(count, query, filter)
    message = "Found #{count}"
    filter = "Reporting" if filter.blank?

    if filter != "All"
      message += " <span class='bold'>#{filter}</span> organizations"
    else
      message += " organizations"
    end
    if query
      message += " matching <span class='bold'>#{query}</span>"
    end

    if query || filter != "Reporting"
      message += ". #{link_to "(Back to reporting organizations)", admin_organizations_url}"
    end

    message.html_safe
  end

  def select_with_all_orgs_plus_user_count(orgs)
    options_for_select(orgs.map{ |o| [organization_name_w_num_users(o), o.id] })
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def organization_response(organization, data_request)
    organization.data_responses.detect { |dr| dr.data_request == data_request }
  end

  def input_options(label = nil, hint = nil, required = false, label_class = 'indented', wrapper_class = 'input-wrapper')
    return  {label: label, hint: hint,
            label_html: { class: label_class, required: required },
            wrapper_html: { class: wrapper_class }}
  end

  def input_date(value, label = nil, hint = nil, required = true, label_class = 'indented', wrapper_class = 'input-wrapper')
    return {value: formatted_date(value), class: "date_picker",
      label: label, required: required,
      hint: hint, label_html: { class: label_class },
      wrapper_html: { class: wrapper_class }}
  end

  def select_options(label = nil, hint = nil, required = true, label_class = 'indented', wrapper_class = 'input-wrapper', input_class = 'string required')
    return {label: label, hint: hint,
      label_html: { class: label_class, required: required},
      wrapper_html: { class: wrapper_class },
      input_html: { class: input_class }}
  end

  def name_hint
    "What is the name of the organization?"
  end

  def raw_type_hint
    "Raw type of organization"
  end

  def funder_type_hint
    "Funder type of organization"
  end

  def implementer_type_hint
    "Implementer type of organization"
  end

  def fosaid_hint
    "Fosaid of organization"
  end

  def currency_hint
    "You can override the currency for individual projects
    should you deem it necessary."
  end

  def contact_name_hint
    "The primary contact at your organization that will help the Health
    Resource Tracker team if there are any questions throughout the process."
  end

  def contact_position_hint
    "The position of the contact at your organization."
  end

  def phone_number_hint
    "A telephone number that can be used to contact the contact person."
  end

  def contact_main_office_phone_number_hint
    "The telephone number of the organizations main office."
  end

  def office_location_hint
    "The geographic location of the office."
  end

  def start_month_hint
    "The month in which your organization's fiscal year starts."
  end
end

app/views/admin/organizations/_buttons.html.haml
%ul.horizontal.button-bar
  %li
    = link_to new_admin_organization_path, :class => "create_alt" do
      = image_tag "new.png"
      Create Organization
  %li
    = link_to "File Import", '#', :id => "csv_file", :class => 'create_alt'
  %li
    = link_to duplicate_admin_organizations_path, :class => 'create_alt' do
      Fix duplicate organizations

app/views/admin/organizations/_filters.html.haml
.section_overlap
  %ul.section_nav
    - ["Reporting", "Non-Reporting", "All"].each do |filter|
      - css_class = "selected" if params[:filter] == filter || (filter == 'Reporting' && params[:filter].blank?)
      %li{:class => css_class}
        = link_to filter, admin_organizations_path({:sort => params[:sort], :direction => params[:direction], :query => params[:query], :filter => filter})

app/views/admin/organizations/_form.html.haml
- activity_managers = @organization.managers
%fieldset.inputs
  %ol
    %li.last
      %ul.section_form
        = f.text_field :name, :label => "Name", :required => true, :hint => "What is the name of the organization?", :label_html => { :class => 'indented' }, :wrapper_html => { :class => 'input-wrapper' }, :size => 50
        = f.select :raw_type, options_for_select(Organization::ORGANIZATION_TYPES, f.object.raw_type), { :include_blank => true  }, :label => 'Type', :hint => 'Raw type of organization', :label_html => { :class => 'indented' }, :input_html => { :class => 'string required' }, :wrapper_html => { :class => 'input-wrapper' }
        = f.select :currency, options_for_select(currency_options_for_select, f.object.currency), { :include_blank => true }, :label => 'Default currency', :hint => 'Select the default currency for your organization', :label_html => { :class => 'indented' }
        = f.text_field :fosaid, :label => "Fosaid", :required => true, :hint => "Fosaid or organization", :label_html => { :class => 'indented' }, :wrapper_html => { :class => 'input-wrapper' }
        %br
        = f.submit @organization.new_record? ? 'Create organization' : 'Update organization', :class => "next update"

    - unless activity_managers.empty?
      %h2 Activity Managers:
      %li.last
        %ul.section_form
          %table.standard
            %thead
              %tr
                %th= sortable "full_name"
                %th= sortable "email"
                %th.login= sortable "last_sign_in_at", "Last login"
                %th= sortable "roles_mask", "Role"
            %tbody
              - activity_managers.each do |user|
                %tr{:class => cycle("even", "odd")}
                  %td= link_to "#{user.full_name}", edit_admin_user_path(user)
                  %td= mail_to user.email
                  %td= last_signin_for(user)
                  %td= user.roles.map{|role| role.humanize}.join(', ')

    - if !@users.blank?
      %h2 Users
      %li.last
        %ul.section_form
          = render "admin/users/users"

    - unless @organization.out_flows.empty?
      %h2 Funder For:
      %li.last
        %ul.section_form
          %table.standard
            %thead
              %tr
                %th Organization
                %th Project
            %tbody
              - @organization.out_flows.each do |of|
                %tr
                  %td= link_to of.organization.name, projects_path
                  %td= link_to of.project.name, edit_project_path(of.project)

    - unless @organization.implementer_splits.empty?
      %h2 Implementer For:
      %li.last
        %ul.section_form
          %table.standard
            %thead
              %tr
                %th Organization
                %th Activity
            %tbody
              - @organization.implementer_splits.each do |is|
                %tr
                  %td= link_to is.organization_name, projects_path
                  %td= link_to is.activity.name, edit_activity_path(is.activity)

- unless @organization.new_record?
  .delete_section
    = link_to "Delete this Organization", admin_organization_path(@organization), :data => { :confirm => "Are you sure you want to delete this Organization?" }, :method => :delete, :class => 'delete_action'
    %p
      %strong Warning:
      Once you delete an Organization, you will lose all data associated with it, and there is no undo.

app/views/admin/organizations/_import.html.haml
#import
  %h3.title_bar Import a CSV file
  .section_form
    %p Create one or more organizations from a CSV file. You can save an Excel spreadsheet as a CSV file through File -> Save As, then select comma separated values (CSV) in the file format box under the file name.

    #import_csv
      = form_tag create_from_file_admin_organizations_path, :multipart => true do
        .upbox
          = label_tag :file, "File"
          = file_field_tag :file
        = submit_tag "Upload and Import", :class => 'small_submit_button'

      = link_to "Download template", download_template_admin_organizations_path, :class => 'create_alt right'

app/views/admin/organizations/_organization.html.haml
- date_format = '%d %b \'%y %H:%M'
- short_date_format = '%d %b \'%y'
- user = organization.current_user_logged_in
%tr
  %td.title= link_to organization.name, edit_admin_organization_path(organization)
  %td= mail_to user.email, user.name if user
  %td= user.last_signin_at.strftime(date_format) if user
  %td= organization.raw_type
  %td= organization.fosaid
  %td= organization.created_at.strftime(short_date_format)
  %td
    %ul.manage_bar
      %li= link_to "Edit", edit_admin_organization_path(organization)
      %li= link_to "x", admin_organization_path(organization), :method => :delete, :data => { :confirm => "Are you sure you want to DELETE this organization? There is no undo." }

app/views/admin/organizations/_organization_info.html.haml
%h2 Preview
.section_form.last
  %table.standard.rounded
    %thead
      %th
      %th
        Duplicate
        %br
        = link_to friendly_name(@duplicate), edit_admin_organization_path(@duplicate)
      %th
        Replacement
        %br
        = link_to friendly_name(@target), edit_admin_organization_path(@target)
      %th
        Merged
        %br
        = friendly_name(@target)

    %tbody
      %tr
        %td Total projects:
        %td= @duplicate.projects.count
        %td= @target.projects.count
        %td= @duplicate.projects.count + @target.projects.count
      %tr
        %td Total activities:
        %td= @duplicate.activities.count
        %td= @target.activities.count
        %td= @duplicate.activities.count + @target.activities.count
      %tr
        %td Total users:
        %td= @duplicate.users.count
        %td= @target.users.count
        %td= @duplicate.users.count + @target.users.count
      %tr
        %td Total (External) Funder References:
        %td= link_to @duplicate.out_flows.length, edit_admin_organization_path(@duplicate)
        %td= link_to @target.out_flows.length, edit_admin_organization_path(@target)
        %td= @duplicate.out_flows.length + @target.out_flows.length
      %tr
        %td Total (External) Funder References:
        %td= link_to @duplicate.implementer_splits.length, edit_admin_organization_path(@duplicate)
        %td= link_to @target.implementer_splits.length, edit_admin_organization_path(@target)
        %td= @duplicate.implementer_splits.length + @target.implementer_splits.length
      - DataRequest.all.each do |request|
        - duplicate_state = @duplicate.responses.with_request(request.id)[0].try(:state)
        - target_state = @target.responses.with_request(request.id)[0].try(:state)
        %tr
          %td= request.name
          %td= duplicate_state || 'N/A'
          %td= target_state || 'N/A'
          %td= DataResponse::States.merged_response_state(duplicate_state, target_state) || 'N/A'

app/views/admin/organizations/duplicate.html.haml
= form_tag remove_duplicate_admin_organizations_path, :remote => true, :method => :put do
  .box{:"data-type" => 'duplicate'}
    = label_tag :duplicate_organization_id, "Potential problem organization (duplicate)"
    = select_tag :duplicate_organization_id, select_with_all_orgs_plus_user_count(@all_organizations)
  .box{:"data-type" => 'target'}
    = label_tag :target_organization_id, "Replacement organization"
    = select_tag :target_organization_id, select_with_all_orgs_plus_user_count(@all_organizations)

  .submit
    // JS event: replace_organization
    = submit_tag "Replace", :id => "replace_organization", :class => "small_submit_button", :data => { :confirm => 'Are you sure' }

  .preview

app/views/admin/organizations/edit.html.haml
%h1.main_heading Edit Organization

= render 'shared/error_messages', :resource => @organization

= form_for @organization, :builder => CustomFormBuilder, :url => admin_organization_path(@organization), :html => {:method => :put, :class => 'basic_form js_form'} do |f|
  = render '/organizations/form', :f => f

app/views/admin/organizations/index.html.haml
- title("Organizations")

%h1.main_heading Organizations
%hr.heading
= render :partial => 'buttons'

= render :partial => 'import'

= render 'filters'

.section_form.wrapped.last.topless
  #search.push
    = form_tag admin_organizations_path, :method => :get do
      = render 'shared/search_form'
  #filter_help.left
    %p= search_and_filter_message(@organizations.total_entries, params[:query], params[:filter])

  - unless @organizations.empty?
    %table.standard
      %thead
        %tr
          %th= sortable "name", "Organization"
          %th Last Login By
          %th Last Login At
          %th= sortable 'raw_type', "Type"
          %th= sortable 'fosaid', "FOSAID"
          %th= sortable "created_at", "Created", true
          %th
      %tbody
        = render :partial => 'organization', :collection => @organizations

    = will_paginate @organizations

app/views/admin/organizations/new.html.haml
%h1.main_heading New Organization

= render 'shared/error_messages', :resource => @organization

%h2 Enter organization information
= form_for @organization, :builder => CustomFormBuilder, :url => admin_organizations_path, :html => {:class => 'basic_form js_form'} do |f|
  = render '/organizations/form', :f => f